# Generated by Django 4.2.3 on 2023-07-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='note',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived?'),
        ),
    ]
